### ISSUE TITLE
Parsing a valid argument with GETOPT_OPTION_TYPE_NO_ARG fails

### ISSUE THREAD

**Issue by feggfegg** [wc-duck/getopt#12]
If you have an argument that's supposed to have no arguments, the getopt_next function still tries to find one. If that's something that doesn't start with a '-' it's considered an argument and an error is returned ("!"). I would expect that if something is TYPE_NO_ARG, whatever comes after should be ignored.

Example: { "foo", 0, GETOPT_OPTION_TYPE_NO_ARG, nullptr, 'f', "do foo things", ""}
Command line that fails: " --foo banana"
Command line that works: " --foo --banana"

Note that the correct argument is actually found, but disqualified with the comment
/* these types should have no argument, usage error! */

**Comment by wc-duck** [comment]
should be fixed now!
