### ISSUE TITLE
char** in getopt_create_context

### ISSUE THREAD

**Issue by kennyalive** [wc-duck/getopt#7]
In c++ main signature uses char** not const char**. I got compilation error because char** can not be converted to const char** that is accepted by getopt_create_context.

**Comment by wc-duck** [comment]
I'm not ready to change this as of now as that would break the API for users. I would also say that it is correct passing it as const as it is not modified by the function (maybe there should have been even more consts?).
As a workaround that might work you can always change the signature of main() to match getopt as all compilers I know accept that.
Feel free to re-open this issue if you want to discuss this more.
